# main.py

"""
2D Stenosis Physics-Informed Deep Operator Network
    Main script and CLI entry point; calls other scripts

Evan Hackstadt
Rugonyi Lab
"""

# Note: initial script generated by Claude Sonnet 4.6


import sys
import argparse
from pathlib import Path
import glob
import json

import numpy as np
import torch
import deepxde as dde

from config import StenosisConfig
from geometry import create_stenosis_mesh, ellipse_bottom, ellipse_mask
from fem import read_mesh, solve_stenosis, fem_predict
from deeponet import *
from analysis import *


# ———————————————— HELPER FUNCTIONS ————————————————

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--re",        type=float, help="Reynolds number")
    parser.add_argument("--n-adam",    type=int,   help="Adam iterations")
    parser.add_argument("--n-lbfgs",   type=int,   help="L-BFGS max iterations")
    parser.add_argument("--mesh-size", type=float, help="FEM mesh element size")
    
    parser.add_argument("--force-mesh", action="store_true",
                        help="Force fresh mesh generation instead of depending on cached file.")
    parser.add_argument("--skip-fem", action="store_true",
                        help="Skip the live FEM solve and instead load from cached file.")
    parser.add_argument("--force-resample-train", action="store_true",
                        help="Force resampling of labeled data for training from FEM ground-truth. Will require a fresh PINN training as well.")
    parser.add_argument("--force-resample-test", action="store_true",
                            help="Force resampling of labeled data for fine-tuning from FEM ground-truth. Will require a fresh PINN fine-tuning as well.")
    parser.add_argument("--force-deeponet", action="store_true",
                        help="Force fresh DeepONet training instead of depending on saved models.")
    parser.add_argument("--analysis-only", action="store_true",
                        help="Perform analysis and visualization ONLY, avoiding costly PINN retraining. Incompatible with force options.")
    
    return parser.parse_args()



# ———————————————— SUB-FUNCTIONS ————————————————
# perform lazy execution of functions from other scripts & save results

# --- 1. Generate Mesh ---
def load_or_cache_mesh(cfg: StenosisConfig, a: float, b: float, force_mesh: bool):
    """
    Generates mesh for a given geometry, unless file already exists.
    Args:
        cfg: custom config object
        a: ellipse semimajor
        b: ellipse semiminor
        force_mesh: whether or not to force re-generation regardless of existing files.
    Returns:
        msh_file: Path to the existing or generated mesh file for the geometry.
    """
    
    tag = cfg.geo_tag(a, b)
    msh_file = cfg.meshes_dir / f"stenosis_{tag}.msh"
    
    # Create mesh if file does not already exist, or forced
    if force_mesh or not msh_file.exists():
        print(f"Generating mesh to be saved to: {msh_file}")
        create_stenosis_mesh(cfg, a, b, msh_file)
    else:
        print(f"Skipping mesh since existing mesh file found: {msh_file.name}")
    
    return msh_file


# --- 2. FEM Solve ---
def load_or_cache_fem(cfg: StenosisConfig, a: float, b: float, 
                      msh_file: Path, skip_fem: bool):
    """
    Solves the system using Finite Element Method for a given geometry, unless solution file already exists.
    Args:
        cfg: custom config object
        a: ellipse semimajor
        b: ellipse semiminor
        msh_file: generated mesh for this geometry
        skip_fem: whether or not to skip the live fem solve.
    Returns:
        fem_data: ground-truth array of shape (nx*ny - ellipse pts, 5) = [x,y,u,v,p]
        msh: mesh loaded from file
        u_sol: if fem not skipped, return FEniCS u solution object
        p_sol: if fem not skipped, return FEniCS p solution object
    """
        
    tag = cfg.geo_tag(a, b)
    fem_file = cfg.fem_dir / f"solution_{tag}.npy"
    
    if skip_fem and fem_file.exists():
        print(f"Skipping FEM since existing FEM file found: {fem_file.name}")
        fem_data = np.load(fem_file, allow_pickle=True).astype(np.float32)
        
        # still process mesh
        msh, _ = read_mesh(msh_file)
        
        return fem_data, None, None, msh
    
    elif not skip_fem:
        
        print(f"Running FEM, solution to be saved to: {fem_file.name}")
        msh, u_sol, p_sol = solve_stenosis(cfg, msh_file)
        
        # Save on a dense evaluation grid for later comparison
        xs = np.linspace(-cfg.L/2, cfg.L/2, cfg.query_nx)
        ys = np.linspace(0, cfg.H_max, cfg.query_ny)
        XX, YY = np.meshgrid(xs, ys)
        flat = np.column_stack([XX.ravel(), YY.ravel()])
        
        # Mask out points inside the ellipse obstruction
        mask = ellipse_mask(flat[:, 0], flat[:, 1], cfg, a, b)
        query = flat[mask]
        
        # Get FEM vals for the uniform query
        fem_data = fem_predict(u_sol, p_sol, msh, query, cfg)    # fem_data also holds query pts
        np.save(fem_file, fem_data)
        print(f"FEM solution saved to {fem_file}")
        
        return fem_data, u_sol, p_sol, msh
        
    else:
        raise ValueError("FEM file not found or incompatible args.")
    


# --- 3. Branch Inputs ---
def load_or_cache_sensors(cfg: StenosisConfig, force: bool = False):
    """
    Load sensor grid from disk or compute and save it.
    The sensor grid must be identical across all training/inference runs.
    Saving it prevents accidental mismatch if SENSOR_NX/NY constants change.
    """
    sensor_path = cfg.data_dir / "deeponet_sensors.csv"
    
    if not force and sensor_path.exists():
        print(f"Loading sensor grid from {sensor_path.name}")
        return np.loadtxt(sensor_path, delimiter=",").astype(np.float32)

    else:
        print(f"Computing sensor grid, saving to {sensor_path.name}")
        sensors = make_sensor_grid(cfg)
        np.savetxt(sensor_path, sensors, delimiter=",")
        return sensors


# --- 4. Trunk Inputs ---
def load_or_cache_trunk(cfg: StenosisConfig, fem_data_dict: dict,
                        u_sol_dict: dict, p_sol_dict: dict,
                        msh_dict: dict, tag: str, force: bool = False):
    """
    Create and return PDE data, trunk points, labeled output array, and extended trunk (with obstacle pts appended)
    
    Parameters
    ----------
        cfg                  : StenosisConfig
        fem_data_dict        : {(a,b): (N_fem_pts, 5)} — cached FEM data (for reference)
        u_sol_dict           : {(a,b): dolfinx velocity solution object}
        p_sol_dict           : {(a,b): dolfinx pressure solution object}
        msh_dict             : {(a,b): dolfinx mesh object}
    """
    
    # PDE data object
    pde_data = build_pde_data_object(cfg.train_geometries, cfg)
    trunk_pts = pde_data.train_x_all
    
    # Per-geometry obstacle points (need for output array)
    print(f"Sampling obstacle points for {len(cfg.train_geometries)} geometries")
    obstacle_pts_by_geom = sample_obstacle_points(cfg, cfg.train_geometries)
    
    # labeled output array
    # extended trunk (query pts + channel boundary pts + obstacle pts from the first geo)
    arr_path = cfg.data_dir / f"deeponet_trunk_labeled_{tag}.npy"
    ext_trunk_path = cfg.data_dir / f"deeponet_trunk_extended_{tag}.csv"
    use_cache = (None in u_sol_dict.values()) or (None in p_sol_dict.values())
    
    if not force and arr_path.exists() and ext_trunk_path.exists():
        print(f"Loading labeled array from {arr_path.name} and extended trunk from {ext_trunk_path.name}")
        output_arr = np.load(arr_path, allow_pickle=True).astype(np.float32)
        extended_trunk = np.loadtxt(ext_trunk_path, delimiter=",").astype(np.float32)
    else:
        if use_cache:
            print(f"Sampling labeled trunk points for {len(cfg.train_geometries)} geometries -> {arr_path.name} *using cached FEM*")
            output_arr, extended_trunk = build_output_array_from_cache(fem_data_dict, 
                                                            trunk_pts, 
                                                            obstacle_pts_by_geom, 
                                                            cfg)
        else:
            print(f"Sampling labeled trunk points for {len(cfg.train_geometries)} geometries -> {arr_path.name}")
            output_arr, extended_trunk = build_output_array(fem_data_dict, 
                                                trunk_pts,
                                                obstacle_pts_by_geom, 
                                                u_sol_dict,
                                                p_sol_dict,
                                                msh_dict,
                                                cfg)
        np.save(arr_path, output_arr)
        np.savetxt(ext_trunk_path, extended_trunk, delimiter=",")
    
    return pde_data, trunk_pts, output_arr, extended_trunk



# --- 5. Train DeepONet ---
def load_or_train_deeponet(cfg: StenosisConfig,
                           pde_data: dde.data.PDE,
                           sensors: np.ndarray,
                           extended_trunk: np.ndarray,
                           output_arr: np.ndarray,
                           force_deeponet: bool):
    """
    Performs main DeepONet training on all training geometries
    Args:
        cfg: custom config object
        pde_data: DeepXDE PDE data object handling trunk points (geometry, PDE loss, channel BCs)
        sensors: array of fixed sensor points (n_sensors, 2) = [x,y]
        extended_trunk: array of trunk inputs ()
        output_arr: FEM- and BC-labeled data array of (n_geom, M + K, 3)
        force_deeponet: whether or not to force retraining from scratch regardless of saved models
    Returns:
        trained_model: DeepXDE model object with trained weights / parameters
    """
    model_prefix = cfg.pinn_dir / "model"
    
    model = build_deeponet_model(cfg.train_geometries, pde_data, sensors,
                                 extended_trunk, output_arr, cfg)
    
    # proxy for train completion: saved model and training log
    existing_models = glob.glob(f"{model_prefix}*.pt")
    log_file = cfg.pinn_dir / "training_log.json"
    rerun = False if len(existing_models) > 0 and log_file.exists() else True
    
    # train / restore
    if force_deeponet or rerun:
        print(f"Training DeepONet, solution to be saved to: {model_prefix.name}")
        cfg.clear_dir(cfg.pinn_dir)     # clear any old models
        trained_model = train_deeponet(model, model_prefix, cfg)
    else:
        print(f"Skipping PINN since existing model(s) found: {existing_models}")
        trained_model = restore_deeponet(model, model_prefix, cfg)
    
    return trained_model



# --- 7. DeepONet Predict on Training Set ---
def deeponet_predict(fem_data_dict, model, sensors, label, cfg: StenosisConfig):
    """
    Evaluate the model on each provided geometry, compare to ground truth, and save errors.
    Args:
        fem_data_dict: dictionary mapping (a, b) --> array of shape (N, 5) = [x,y,u,v,p] 
        model: a DeepXDE model object to use for prediction (can be baseline, finetuned, etc.)
        sensors: array of fixed sensor points (n_sensors, 2) = [x, y]
        label: either "train" or "test" to distinguish error file
        cfg: custom config object
    Returns:
        deeponet_data_dict: dictionary mapping geometries --> deeponet_data array of shape (N, 5) = [x,y,u,v,p], 
        summary_path: Path to summary_{tag}.json
    """
    all_errors = {}
    deeponet_data_dict = {}
    
    for (a, b), fem_data in fem_data_dict.items():
        print(f"Predicting on geometry ({a}, {b})")
        output_dir = cfg.geo_dir(a, b)
        tag = cfg.geo_tag(a, b)
        
        # predict
        query_pts = fem_data[:, 0:2]
        deeponet_data = deeponet_predict(model, sensors, cfg, a, b, query_pts)
        errors = compute_errors(deeponet_data, fem_data)
        
        # log
        save_errors(errors, output_dir, a, b)
        deeponet_data_dict[(a, b)] = deeponet_data
        all_errors[tag] = errors
    
    # Save errors
    summary_path = cfg.summary_dir / f"error_summary_{label}.json"
    with summary_path.open("w") as f:
        json.dump(all_errors, f, indent=2)
        
    return deeponet_data_dict, summary_path
    


# --- 9. Visualization ---
def visualization(deeponet_data_dict_train, deeponet_data_dict_test, 
                  fem_data_dict_train, fem_data_dict_test, 
                  train_error_summary_path, test_error_summary_path,
                  cfg: StenosisConfig):
    """
    Perform a variety of analyses and visualizations to evaluate the trained PINN
    Args:
        deeponet_data_dict_train: dictionary mapping training geo_tags -->  deeponet_data array of shape (N, 5) = [x,y,u,v,p] 
        deeponet_data_dict_test:  dictionary mapping testing geo_tags  -->  deeponet_data array of shape (N, 5) = [x,y,u,v,p] 
        fem_data_dict_train:  dictionary mapping training geo_tags -->  fem_data array of shape (N, 5) = [x,y,u,v,p] 
        fem_data_dict_test:   dictionary mapping testing geo_tags  -->  fem_data array of shape (N, 5) = [x,y,u,v,p] 
        train_error_summary_path: Path to the summary_train.json error log
        test_error_summary_path:  Path to the summary_test.json error log
        cfg: custom config object
    """
    
    
    # TRAIN geometries - per-geometry analyses
    for (a, b) in deeponet_data_dict_train.keys():
        print(f"Visualizing training geometry ({a}, {b})")
        
        output_dir = cfg.geo_dir(a, b)
        tag = cfg.geo_tag(a, b)
        deeponet_data = deeponet_data_dict_train[(a, b)]
        fem_data = fem_data_dict_train[(a, b)]
        
        plot_domain(cfg, a, b, output_dir)
        plot_output_heatmaps(deeponet_data, fem_data, cfg, tag, output_dir, a, b, separate_plots=False)
        plot_error_heatmaps(deeponet_data, fem_data, cfg, tag, output_dir, a, b, separate_plots=False)
        plot_velocity_quiver(deeponet_data, fem_data, cfg, tag, output_dir, a, b)
    
    
    # TEST geometries - per-geometry, per-strategy analyses
    for (a, b) in deeponet_data_dict_test.keys():
        print(f"Visualizing testing geometry ({a}, {b})")
        
        output_dir = cfg.geo_dir(a, b)
        tag = cfg.geo_tag(a, b)
        
        plot_domain(cfg, a, b, output_dir)
        
        # baseline
        output_dir_baseline = cfg.geo_dir(a, b) / "baseline"
        deeponet_data = deeponet_data_dict_test[(a, b)]["baseline"]
        fem_data = fem_data_dict_test[(a, b)]
        
        plot_output_heatmaps(deeponet_data, fem_data, cfg, tag, 
                             output_dir_baseline, a, b, separate_plots=False)
        plot_error_heatmaps(deeponet_data, fem_data, cfg, tag, 
                            output_dir_baseline, a, b, separate_plots=False)
        plot_velocity_quiver(deeponet_data, fem_data, cfg, tag,
                             output_dir_baseline, a, b)
        
        '''
        strategy_labels = ["baseline"]
        deeponet_data_list = [deeponet_data]
        
        # fine-tuning strategies
        for strategy, params in cfg.finetune_strategies.items():
            output_dir_strat = cfg.geo_dir(a, b) / strategy
            deeponet_data = deeponet_data_dict_test[(a, b)][strategy]
            
            plot_output_heatmaps(deeponet_data, fem_data, cfg, tag, 
                                 output_dir_strat, a, b, separate_plots=False)
            plot_error_heatmaps(deeponet_data, fem_data, cfg, tag, 
                                output_dir_strat, a, b, separate_plots=False)
            plot_velocity_quiver(deeponet_data, fem_data, cfg, tag,
                                 output_dir_strat, a, b)

            strategy_labels.append(strategy)
            deeponet_data_list.append(deeponet_data)
            
            # plot loss curves
            if params["finetune"]:
                # determine loss terms based on strategy
                if params["hardbc"]:
                    loss_term_labels = ["PDE (continuity)", "PDE (x-momentum)", "PDE (y-momentum)",
                                        "BC (wall u)", "BC (wall v)", "BC (obstacle u)", "BC (obstacle v)"]
                else:
                    loss_term_labels = ["PDE (continuity)", "PDE (x-momentum)", "PDE (y-momentum)", 
                                        "BC (inlet u)", "BC (inlet v)", "BC (wall u)", "BC (wall v)", 
                                        "BC (obstacle u)", "BC (obstacle v)", "BC (outlet p)"]
                obs_labels = ["BC (observed u)", "BC (observed v)", "BC (observed p)"]
                loss_term_labels.extend([obs_labels[i] for i in cfg.test_observation_components])
                
                loss_file = cfg.pinn_dir / strategy / cfg.geo_tag(a,b) / "loss.dat"
                loss_data = np.loadtxt(loss_file, delimiter=" ", comments="#")
                plot_loss_curves(loss_data, loss_file.parent, loss_term_labels)

        # stacked strategy comparisons across all finetuning models for this geometry
        plot_output_heatmaps_multi(deeponet_data_list, fem_data, cfg, tag, 
                                    cfg.geo_dir(a, b) / "comparison",
                                    a=a, b=b,
                                    strategy_labels=strategy_labels,
                                    fem_row_label="FEM")
        plot_velocity_quiver_multi(deeponet_data_list, fem_data, cfg, tag,
                                   cfg.geo_dir(a, b) / "comparison",
                                   a=a, b=b, 
                                   strategy_labels=strategy_labels,
                                   fem_row_label="FEM")
        plot_error_heatmaps_multi(deeponet_data_list, fem_data, cfg, tag, 
                                    cfg.geo_dir(a, b) / "comparison",
                                    a=a, b=b,
                                    strategy_labels=strategy_labels)
        
    '''  
    print(f"Per-Geometry analysis and visualization complete.")
    
    
    # GLOBAL analyses
    
    # visualize all geometries overlayed
    plot_all_domains(cfg, cfg.results_dir)
    
    # plot main training loss curves
    loss_data = np.loadtxt(cfg.pinn_dir / "loss.dat", delimiter=" ", comments="#")
    plot_loss_curves(loss_data, cfg.pinn_dir)
    
    # compare train & test errors separately
    output_dir = cfg.summary_dir / "train"
    plot_error_comparison(train_error_summary_path, output_dir, cfg, 
                          parameter="ab", fixed_strat=None, strategies=["train"])
    
    output_dir = cfg.summary_dir / "test"
    test_strats = ["baseline"] + list(cfg.finetune_strategies.keys())
    plot_error_comparison(test_error_summary_path, output_dir, cfg, 
                          parameter="ab", fixed_strat=None, 
                          strategies=test_strats)
    plot_error_comparison(test_error_summary_path, output_dir, cfg, 
                          parameter="strategy", fixed_ab=None,
                          strategies=test_strats)
    plot_error_comparison_2d(test_error_summary_path, output_dir, cfg, 
                             strategy_order=test_strats)
    
    # compare train + test errors side-by-side
    with open(train_error_summary_path, "r", encoding="utf-8") as f:
        train_errors = json.load(f)
    with open(test_error_summary_path, "r", encoding="utf-8") as f:
        test_errors = json.load(f)
    all_errors = train_errors | test_errors
    
    all_error_summary_path = train_error_summary_path.parent / "error_summary_all.json"
    with open(all_error_summary_path, "w", encoding="utf-8") as f:
        json.dump(all_errors, f, indent=2)
    
    output_dir = cfg.summary_dir / "all"
    all_strategies = ["train"] + test_strats
    plot_error_comparison(all_error_summary_path, output_dir, cfg, parameter="ab",
                          fixed_strat=None, strategies=all_strategies)
    plot_error_comparison(all_error_summary_path, output_dir, cfg, parameter="strategy",
                          fixed_ab=None, strategies=all_strategies)
    plot_error_comparison_2d(all_error_summary_path, output_dir, cfg,
                             strategy_order=all_strategies)
    
    # log config
    config_dict = cfg.config_as_dict()
    config_path = cfg.results_dir / "config_log.json"
    with config_path.open("w", encoding="utf-8") as f:
        json.dump(config_dict, f, indent=2)
    
    print(f"Global analysis and visualization complete.")
    
    

    

# ———————————————— MAIN ————————————————
# top-level overview of pipeline & handle args

def main():
    
    # Stage 0: Args and Print
    args = parse_args()
    cfg  = StenosisConfig()

    # Override config with CLI args
    if args.re:
        cfg.Re = args.re
    if args.n_adam:
        cfg.n_adam = args.n_adam
    if args.n_lbfgs:
        cfg.n_lbfgs = args.n_lbfgs
    if args.mesh_size:
        cfg.mesh_size = args.mesh_size
    
    # downstream dependencies
    if args.force_resample_train:
        args.force_deeponet = True
    if args.force_resample_test or args.force_deeponet:
        args.force_finetune = True
    
    # Validate geometry split
    for tup in cfg.train_geometries:
        if tup in cfg.test_geometries:
            raise ValueError(f"Duplicate geometries found in train and test geometries.\nTrain={cfg.train_geometries}\nTest={cfg.test_geometries}")
    
    # Print to terminal
    print(f"\n{'='*50}\nEXECUTION PLAN\n{'='*50}")
    print(f"\nTrain geometries={cfg.train_geometries}")
    print(f"\nTest geometries{cfg.test_geometries}")
    if args.analysis_only:
        print(f"\n1. Analysis ONLY. Skipping mesh, FEM, and PINN. Analyzing complete cases only.")
    else:
        print(f"\n1. Generate meshes for each geometry (forced = {args.force_mesh})")
        print(f"2. Solve FEM ground truth for each geometry (forced = {args.skip_fem})")
        print(f"3. Assemble branch data (SDF at sensor points, train and test geometries)")
        print(f"4. Assemble trunk data (extended trunk data, train geometries)")
        print(f"5. Construct PointSetBCs for the channel boundary conditions")
        print(f"6. Build and Train DeepONet on {len(cfg.train_geometries)} training geometries (forced = {args.force_deeponet})")
        print(f"6. Validate DeepONet on training geometries")
        print(f"8. Test DeepONet on testing geometries")
        print(f"9. Perform analysis and visualization")
    
    
    # Perform only analysis on complete cases if requested
    if args.analysis_only:
        pass                    # TODO
    
    else:
    
        cfg.make_all_dirs()
        
        # Stages 1-2: Generate meshes and ground-truth FEM for train + test geometries
        fem_data_dict_train = {}
        fem_data_dict_test  = {}
        fem_sol_objects_train = {'u': {}, 'p': {}, 'msh': {}}
        fem_sol_objects_test  = {'u': {}, 'p': {}, 'msh': {}}
        
        for (a, b) in cfg.train_geometries:
            msh_file = load_or_cache_mesh(cfg, a, b, args.force_mesh)
            fem_data, msh, u_sol, p_sol = load_or_cache_fem(cfg, a, b, msh_file, args.skip_fem)
            
            fem_data_dict_train[(a, b)] = fem_data
            fem_sol_objects_train['u'][(a, b)] = u_sol
            fem_sol_objects_train['p'][(a, b)] = p_sol
            fem_sol_objects_train['msh'][(a, b)] = msh
        
        for (a, b) in cfg.test_geometries:
            msh_file = load_or_cache_mesh(cfg, a, b, args.force_mesh)
            fem_data, msh, u_sol, p_sol = load_or_cache_fem(cfg, a, b, msh_file, args.skip_fem)
            
            fem_data_dict_test[(a, b)] = fem_data
            fem_sol_objects_test['u'][(a, b)] = u_sol
            fem_sol_objects_test['p'][(a, b)] = p_sol
            fem_sol_objects_test['msh'][(a, b)] = msh

        
        # Stage 3: Branch Inputs (build sensor grid and evaluate SDF for each geo)
        sensors = load_or_cache_sensors(cfg)
        
        # Stage 4: Trunk Inputs (obstacle points, PDE data, output array)
        
        
        # Stage 4: Trunk Inputs: intersection mask
        pde_data, trunk_train, output_arr_train, ext_trunk_train = load_or_cache_trunk(
            cfg, fem_data_dict_train,
            fem_sol_objects_train['u'],
            fem_sol_objects_train['p'],
            fem_sol_objects_train['msh'],
            "train",
        )
        
        
        # Stage 5: Build and Train DeepONet
        trained_model = load_or_train_deeponet(cfg, pde_data, sensors, ext_trunk_train, 
                                               output_arr_train, args.force_deeponet)
        
        
        # Stage 6: Evaluate on Training Geometries
        deeponet_data_dict_train, summary_train = deeponet_predict(fem_data_dict_train, 
                                                                   trained_model, 
                                                                   sensors, 
                                                                   "train", 
                                                                   cfg)
        # Stage 8: Evaluate on Testing Geometries
        deeponet_data_dict_test, summary_test = deeponet_predict(fem_data_dict_test, 
                                                                 trained_model, 
                                                                 sensors, 
                                                                 "test", 
                                                                 cfg)
        
        
        # Stage 9: Analysis and Visualization
        visualization(deeponet_data_dict_train, deeponet_data_dict_test,
                      fem_data_dict_train, fem_data_dict_test,
                      summary_train, summary_test, cfg)
        
        print(f"\n{'='*50}\nPIPELINE COMPLETE\n{'='*50}")
    


if __name__ == "__main__":
    main()