# main.py

"""
2D Parameterized Stenosis
    Main script and CLI entry point; calls other scripts

Evan Hackstadt
Rugonyi Lab
"""

# Note: initial script generated by Claude Sonnet 4.6


import json
import argparse
from pathlib import Path
import glob

import numpy as np
import torch
import deepxde as dde

from config import StenosisConfig
from geometry import create_stenosis_mesh, ellipse_bottom, ellipse_mask
from fem import solve_stenosis, fem_predict
from data import build_interior_dataset, build_labeled_dataset
from pinn import build_model, train_model, restore_model, pinn_predict
from analysis import (compute_errors, save_errors,
                      plot_loss_curves, plot_domain,
                      plot_output_heatmaps, plot_error_heatmaps,
                      plot_error_comparison, plot_error_comparison_2d)


# ———————————————— HELPER FUNCTIONS ————————————————

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--re",        type=float, help="Reynolds number")
    parser.add_argument("--n-adam",    type=int,   help="Adam iterations")
    parser.add_argument("--n-lbfgs",   type=int,   help="L-BFGS max iterations")
    parser.add_argument("--mesh-size", type=float, help="FEM mesh element size")
    
    parser.add_argument("--force-mesh", action="store_true",
                        help="Force fresh mesh generation instead of depending on cached file.")
    parser.add_argument("--force-fem", action="store_true",
                        help="Force fresh FEM solve instead of depending on cached file.")
    parser.add_argument("--force-resample", action="store_true",
                        help="Force resampling of labeled data from FEM ground-truth. Will require a fresh PINN training as well.")
    parser.add_argument("--force-pinn", action="store_true",
                        help="Force fresh PINN training instead of depending on saved models.")
    parser.add_argument("--analysis-only", action="store_true",
                        help="Perform analysis and visualization ONLY, avoiding costly PINN retraining. Incompatible with force options.")
    
    return parser.parse_args()


def case_complete(cfg: StenosisConfig, n: int):
    n_dirs = cfg.n_dirs(n)
    error_path = n_dirs['base'] / "errors.json"
    plot_dir = n_dirs['plots']

    if error_path.is_file():
        return True
    if plot_dir.is_dir():
        for fname in plot_dir.iterdir():
            if fname.is_file():
                return True
    return False


def load_case_errors(cfg: StenosisConfig, n: int):
    error_path = cfg.n_dirs(n)['base'] / "errors.json"
    if error_path.is_file():
        with error_path.open("r", encoding="utf-8") as f:
            return json.load(f)
    return {
        "status": "skipped",
        "message": "Skipped because existing outputs were detected, but errors.json was not present."
    }


# ———————————————— SUB-FUNCTIONS ————————————————

# --- Generate Mesh ---
def mesh(cfg: StenosisConfig, a: float, b: float, force_mesh: bool):
    
    tag = cfg.geo_tag(a, b)
    msh_file = cfg.meshes_dir / f"stenosis_{tag}.msh"
    
    # Create mesh if file does not already exist, or forced
    if force_mesh or not msh_file.exists():
        print(f"Generating mesh to be saved to: {msh_file}")
        create_stenosis_mesh(cfg, a, b, msh_file)
    else:
        print(f"Skipping mesh since existing mesh file found: {msh_file.name}")
    
    return msh_file


# --- FEM Solve ---
def fem(cfg: StenosisConfig, a: float, b: float, msh_file: Path, force_fem: bool):

    tag = cfg.geo_tag(a, b)
    fem_file = cfg.fem_dir / f"solution_{tag}.npz"
    
    if force_fem or not fem_file.exists():
        
        print(f"Running FEM, solution to be saved to: {fem_file}")
        msh, u_sol, p_sol = solve_stenosis(cfg, msh_file)
        
        # Save on a dense evaluation grid for later comparison
        xs = np.linspace(-cfg.L/2, cfg.L/2, cfg.nx)
        ys = np.linspace(0, cfg.H_max, cfg.ny)
        XX, YY = np.meshgrid(xs, ys)
        flat = np.column_stack([XX.ravel(), YY.ravel()])
        
        # Mask out points inside the ellipse obstruction
        mask = ellipse_mask(flat[:, 0], flat[:, 1], cfg, a, b)
        query = flat[mask]
        
        # Get FEM vals for the uniform query
        fem_data = fem_predict(u_sol, p_sol, msh, query, cfg)    # fem_data also holds query pts
        np.savez(fem_file, data=fem_data)
        print(f"FEM solution saved to {fem_file}")
        
    else:
        print(f"Skipping FEM since existing FEM file found: {fem_file.name}")

    # Reload regardless
    fem_file = np.load(fem_file, allow_pickle=True)
    fem_data = fem_file['data']
    
    return fem_data


# --- Sample Labeled Points Across Geometries ---
def sample_labeled_data(cfg: StenosisConfig, fem_data_dict_train: dict, 
                        fem_data_dict_test: dict, force_resample: bool):

    train_file = cfg.fem_dir / f"labeled_data_train_geometries.csv"
    test_file  = cfg.fem_dir / f"labeled_data_test_geometries.csv"
    
    # for training
    if force_resample or not train_file.exists():
        print(f"Sampling labeled training points, will be saved to: {train_file}")
        all_labeled_data = build_labeled_dataset(fem_data_dict_train, cfg.n_labeled_train, cfg)
        np.savetxt(train_file, all_labeled_data, delimiter=",")
    else:
        print(f"Skipping labeled training points sampling since existing points file found: {train_file.name}")
    
    # for testing fine-tuning
    if force_resample or not test_file.exists():
        print(f"Sampling observations for testing, will be saved to: {test_file}")
        all_labeled_data = build_labeled_dataset(fem_data_dict_test, cfg.n_labeled_test, cfg)
        np.savetxt(test_file, all_labeled_data, delimiter=",")
    else:
        print(f"Skipping observations for testing sampling since existing points file found: {test_file.name}")
    
    # Reload regardless
    all_labeled_data_train = np.loadtxt(train_file, delimiter=",")
    all_labeled_data_test  = np.loadtxt(test_file, delimiter=",")
    
    return all_labeled_data_train, all_labeled_data_test
        

# --- Train PINN ---
def pinn_train(interior_data, boundary_data, labeled_data, cfg: StenosisConfig, force_pinn: bool):
    
    model_prefix = cfg.pinn_dir / "model"
    
    # proxy for PINN completion: saved model and training log
    existing_models = glob.glob(f"{model_prefix}*.pt")
    log_file = cfg.pinn_dir / "training_log.json"
    rerun = False if len(existing_models) > 0 and log_file.exists() else True
    
    if force_pinn or rerun:
        print(f"Training PINN, solution to be saved to: {model_prefix}")
        cfg.clear_dir(cfg.pinn_dir)     # clear any old models
        model = build_model(interior_data, boundary_data, labeled_data, cfg)
        final_model = train_model(model, model_prefix, cfg)
    else:
        print(f"Skipping PINN since existing model(s) found: {existing_models}")
        model = build_model(interior_data, boundary_data, labeled_data, cfg)
        final_model = restore_model(model, model_prefix, cfg)
    
    return final_model


# --- Analysis & Visualization ---
def analysis(fem_data_dict_train, fem_data_dict_test, model, labeled_data, cfg: StenosisConfig):
    """
    Perform a variety of analyses and visualizations to evaluate the trained PINN
    Args:
        fem_data_dict_train: dictionary mapping training geo_tags --> fem_data array of shape (N, 5) = [x,y,u,v,p] 
        fem_data_dict_test:  dictionary mapping testing geo_tags -->  fem_data array of shape (N, 5) = [x,y,u,v,p] 
        model: DeepXDE model object holding the trained and frozen PINN
        labeled_data: array of shape (n_labeled_train * n_geometries, 7) = [x,y,a,b, u,v,p]
        cfg: custom config object
    """
    
    all_errors = {}
    
    # TRAIN geometries - per-geometry analyses
    for (a, b), fem_data in fem_data_dict_train.items():
        
        output_dir = cfg.plots_geo_dir(a, b)
        tag = cfg.geo_tag(a, b)
        
        # one-shot PINN prediction
        query = fem_data[:, 0:4]    # [x,y,a,b]
        pinn_data = pinn_predict(model, query)
        
        # errors
        errors = compute_errors(pinn_data, fem_data)
        save_errors(errors, output_dir, a, b)
        all_errors[tag] = errors
        all_errors[tag]["parameters"] = {"a": a, "b": b}
        all_errors[tag]["partition"] = "train"
        
        # plot
        plot_domain(cfg, a, b, output_dir, labeled_data)
        plot_output_heatmaps(pinn_data, fem_data, cfg, tag, output_dir, a, b, separate_plots=False)
        plot_error_heatmaps(pinn_data, fem_data, cfg, tag, output_dir, a, b, separate_plots=False)
    
    # TEST geometries - per-geometry analyses
    for (a, b), fem_data in fem_data_dict_test.items():
        
        output_dir = cfg.plots_geo_dir(a, b)
        tag = cfg.geo_tag(a, b)
        
        # one-shot PINN prediction
        query = fem_data[:, 0:4]
        pinn_data = pinn_predict(model, query)
        errors = compute_errors(pinn_data, fem_data)
        save_errors(errors, output_dir, a, b)
        all_errors[tag] = errors
        all_errors[tag]["parameters"] = {"a": a, "b": b}
        all_errors[tag]["partition"] = "test"
        
        # plot
        plot_domain(cfg, a, b, output_dir, labeled_pts=None)     # TODO add test observation points here
        plot_output_heatmaps(pinn_data, fem_data, cfg, tag, output_dir, a, b, separate_plots=False)
        plot_error_heatmaps(pinn_data, fem_data, cfg, tag, output_dir, a, b, separate_plots=False)
        
        # fine-tuned PINN prediction on test case observations — TODO
        #
    
    print(f"Per-Geometry analysis and visualization complete.")
    
    # GLOBAL analyses
    
    # plot loss curves
    loss_data = np.loadtxt(cfg.pinn_dir / "loss.dat", delimiter=" ", comments="#")
    plot_loss_curves(loss_data, cfg.plots_dir)
    
    # log errors
    cfg.summary_dir.mkdir(parents=True, exist_ok=True)
    summary_path = cfg.results_dir / "summary.json"
    with summary_path.open("w") as f:
        json.dump(all_errors, f, indent=2)
    
    # compare errors
    plot_error_comparison(summary_path, cfg.summary_dir, parameter="ab", fixed_n=cfg.n_labeled_train)
    
    # log config
    config_dict = cfg.config_as_dict()
    config_path = cfg.results_dir / "config_log.json"
    with config_path.open("w", encoding="utf-8") as f:
        json.dump(config_dict, f, indent=2)
    
    print(f"Global analysis and visualization complete.")
    
    

    

# ———————————————— MAIN ————————————————

def main():
    
    # Stage 0: Args and Print
    args = parse_args()
    cfg  = StenosisConfig()

    # Override config with CLI args
    if args.re:
        cfg.Re = args.re
    if args.n_adam:
        cfg.n_adam = args.n_adam
    if args.n_lbfgs:
        cfg.n_lbfgs = args.n_lbfgs
    if args.mesh_size:
        cfg.mesh_size = args.mesh_size
    
    if args.force_resample:
        args.force_pinn = True
    
    # Validate geometry split
    for tup in cfg.train_geometries:
        if tup in cfg.test_geometries:
            raise ValueError(f"Duplicate geometries found in train and test geometries.\nTrain={cfg.train_geometries}\nTest={cfg.test_geometries}")
    
    # Print to terminal
    print(f"\n{'='*50}\nEXECUTION PLAN\n{'='*50}")
    print(f"\nTrain geometries={cfg.train_geometries}\nn_labeled_train={cfg.n_labeled_train}")
    print(f"\nTest geometries{cfg.test_geometries}\nn_labeled_test={cfg.n_labeled_test}")
    if args.analysis_only:
        print(f"\n1. Analysis ONLY. Skipping mesh, FEM, and PINN. Analyzing complete cases only.")
    else:
        print(f"\n1. Generate meshes for each geometry (forced = {args.force_mesh})")
        print(f"2. Solve FEM ground truth for each geometry (forced = {args.force_fem})")
        print(f"3. Assemble data (interior, boundary, and labeled points) across all geometries (forced labeled resampling = {args.force_resample})")
        print(f"4. Train PINN on {len(cfg.train_geometries)} training geometries (forced = {args.force_pinn})")
        print(f"5. Test PINN on {len(cfg.test_geometries)} testing geometries (forced = {args.force_pinn})")
    
    
    # 
    
    # Stage 1-2: Generate meshes and ground-truth FEM for train + test geometries
    cfg.make_all_dirs()
    
    fem_data_dict_train = {}
    fem_data_dict_test  = {}
    
    for (a, b) in cfg.train_geometries:
        msh_file = mesh(cfg, a, b, args.force_mesh)
        fem_data = fem(cfg, a, b, msh_file, args.force_fem)
        fem_data_dict_train[(a, b)] = fem_data
    
    for (a, b) in cfg.test_geometries:
        msh_file = mesh(cfg, a, b, args.force_mesh)
        fem_data = fem(cfg, a, b, msh_file, args.force_fem)
        fem_data_dict_test[(a, b)] = fem_data

    
    # Stage 3: Assemble data
    interior_data, boundary_data = build_interior_dataset(cfg)
    labeled_data_train, labeled_data_test = sample_labeled_data(cfg, fem_data_dict_train,
                                                                      fem_data_dict_test, args.force_resample)
    
    # Stage 4: Build and train PINN
    model = pinn_train(interior_data, boundary_data, labeled_data_train, cfg, args.force_pinn)
    
    
    # Stage 5: Perform analysis & visualization
    analysis(fem_data_dict_train, fem_data_dict_test, model, labeled_data_train, cfg)
    
    
    # Perform only analysis if requested        TODO
    if args.analysis_only:
        pass
    


if __name__ == "__main__":
    main()