# geometry.py

"""
2D Parameterized Stenosis
    Geometry functions to generate mesh and handle ellipse geometry

Spatial domain:
    2D rectangle (L, H_MAX) obstructed by an ellipse on the top wall
    Explicitly defined with CSG Difference

Known Values:
    L, H_MAX
    ellipse x_c, y_c, a, b
    Reynold's number Re (default=100)
    Inlet pressure (default=1.0)
    Outlet pressure (default=0.0)

Evan Hackstadt
Rugonyi Lab
"""

# Note: scripts initially generated by Claude Sonnet 4.6


import numpy as np
import gmsh



# --- Define Ellipse Curve / Channel Height ---
def ellipse_bottom(x_arr, cfg, a, b):
    """
    Lower boundary of the ellipse at each x location in x_arr.
    Returns y_bottom of ellipse if x in ellipse domain, else H.
    Note that channel height = H(x) = ellipse_bottom(x).
    """
    dx = x_arr - cfg.x_c
    inside = np.abs(dx) < a
    y_bottom = np.where(
        inside,
        cfg.y_c - b * np.sqrt(np.maximum(1 - (dx / a) ** 2, 0)),
        cfg.H_max
    )
    return y_bottom


# --- Mask Out Points Inside Ellipse ---
def ellipse_mask(xs, ys, cfg, a, b):
    """Returns boolean array, True where pts are outside (or on) the ellipse."""
    # interior condition: (x/a)^2 + (y/b)^2 < 1
    return (
        ((xs - cfg.x_c) / a) ** 2 +
        ((ys - cfg.y_c) / b) ** 2
    ) >= 1.0


# --- Generate Mesh ---
def create_stenosis_mesh(cfg, a, b, filename):
    """
    Parametric stenotic channel mesh.
    cfg: custom config class containing L, H, x_c, y_c, mesh_sze
    a, b: ellipse semi-axes (x, y)
    mesh_size: target element size (reduce for finer mesh)
    """
    L, H, x_c, y_c, mesh_size = cfg.L, cfg.H_max, cfg.x_c, cfg.y_c, cfg.mesh_size
    
    gmsh.initialize()
    gmsh.model.add("stenosis")

    # --- Channel corners ---
    p_bl = gmsh.model.geo.addPoint(-L/2, 0, 0, mesh_size)   # bottom-left
    p_br = gmsh.model.geo.addPoint( L/2, 0, 0, mesh_size)   # bottom-right
    p_tr = gmsh.model.geo.addPoint( L/2, H, 0, mesh_size)   # top-right
    p_tl = gmsh.model.geo.addPoint(-L/2, H, 0, mesh_size)   # top-left

    # --- Ellipse points ---
    p_ec = gmsh.model.geo.addPoint(x_c,     y_c,     0, mesh_size/2)  # center
    p_el = gmsh.model.geo.addPoint(x_c - a, y_c,     0, mesh_size/2)  # left tip
    p_er = gmsh.model.geo.addPoint(x_c + a, y_c,     0, mesh_size/2)  # right tip
    p_eb = gmsh.model.geo.addPoint(x_c,     y_c - b, 0, mesh_size/2)  # bottom tip

    # --- Lines ---
    l_bottom    = gmsh.model.geo.addLine(p_bl, p_br)
    l_outlet    = gmsh.model.geo.addLine(p_br, p_tr)
    l_top_right = gmsh.model.geo.addLine(p_tr, p_er)
    l_top_left  = gmsh.model.geo.addLine(p_el, p_tl)
    l_inlet     = gmsh.model.geo.addLine(p_tl, p_bl)

    # --- Ellipse arcs ---
    # arc1: p_er -> p_eb (right tip down to bottom)
    # arc2: p_eb -> p_el (bottom up to left tip)
    # majorAxisPoint = p_er (the semi-major axis reference, must be on major axis)
    arc1 = gmsh.model.geo.addEllipseArc(p_er, p_ec, p_er, p_eb)
    arc2 = gmsh.model.geo.addEllipseArc(p_eb, p_ec, p_er, p_el)

    # --- Verify connectivity before building loop ---
    # Walk the intended loop and confirm end->start chaining:
    # l_bottom:    p_bl -> p_br
    # l_outlet:    p_br -> p_tr
    # l_top_right: p_tr -> p_er  (reversed: -l_top_right goes p_er -> p_tr... 
    #                              so we need it forward here)
    # arc1:        p_er -> p_eb
    # arc2:        p_eb -> p_el
    # l_top_left:  p_el -> p_tl
    # l_inlet:     p_tl -> p_bl  ✓ closes the loop

    loop = gmsh.model.geo.addCurveLoop([
        l_bottom,
        l_outlet,
        l_top_right,   # traversed p_tr -> p_er (reversed)
        arc1,           # traversed p_eb -> p_er (reversed)
        arc2,           # traversed p_el -> p_eb (reversed)
        l_top_left,     # traversed p_tl -> p_el (reversed)
        l_inlet,        # traversed p_bl -> p_tl (reversed)
    ])
    surface = gmsh.model.geo.addPlaneSurface([loop])

    gmsh.model.geo.synchronize()

    # --- Physical groups ---
    gmsh.model.addPhysicalGroup(1, [l_inlet],                    tag=1, name="inlet")
    gmsh.model.addPhysicalGroup(1, [l_outlet],                   tag=2, name="outlet")
    gmsh.model.addPhysicalGroup(1, [l_bottom],                   tag=3, name="bottom_wall")
    gmsh.model.addPhysicalGroup(1, [l_top_left, l_top_right],    tag=4, name="top_wall")
    gmsh.model.addPhysicalGroup(1, [arc1, arc2],                 tag=5, name="obstacle")
    gmsh.model.addPhysicalGroup(2, [surface],                    tag=6, name="fluid")

    # --- Mesh refinement near obstacle ---
    gmsh.model.mesh.field.add("Distance", 1)
    gmsh.model.mesh.field.setNumbers(1, "CurvesList", [arc1, arc2])
    gmsh.model.mesh.field.add("Threshold", 2)
    gmsh.model.mesh.field.setNumber(2, "InField",  1)
    gmsh.model.mesh.field.setNumber(2, "SizeMin",  mesh_size / 4)
    gmsh.model.mesh.field.setNumber(2, "SizeMax",  mesh_size)
    gmsh.model.mesh.field.setNumber(2, "DistMin",  0.05)
    gmsh.model.mesh.field.setNumber(2, "DistMax",  0.3)
    gmsh.model.mesh.field.setAsBackgroundMesh(2)

    gmsh.model.mesh.generate(2)
    gmsh.write(filename)
    gmsh.finalize()
    print(f"Mesh written to {filename}")