# main.py

"""
2D Parameterized Stenosis
    Main script and CLI entry point; calls other scripts
Evan Hackstadt
Rugonyi Lab
"""

# Note: bulk of the script generated by Claude Sonnet 4.6
# Note: script currently cannot train over multiple geometries; 
#       rather it can just run multiple independently


import os
import re
import json, yaml
import time, datetime
import argparse

import numpy as np
import torch
import deepxde as dde

from config import StenosisConfig
from geometry import create_stenosis_mesh, ellipse_bottom, ellipse_mask
from fem import solve_stenosis, fem_predict
from pinn import build_model, train_model, restore_model, pinn_predict
from analysis import (compute_errors, save_errors,
                      plot_loss_curves, plot_domain,
                      plot_output_heatmaps, plot_error_heatmaps)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--re",        type=float, help="Reynolds number")
    parser.add_argument("--n-adam",    type=int,   help="Adam iterations")
    parser.add_argument("--n-lbfgs",   type=int,   help="L-BFGS iterations")
    parser.add_argument("--mesh-size", type=float, help="FEM mesh element size")
    parser.add_argument("--skip-fem",  action="store_true",
                        help="Skip FEM solve (use cached results)")
    parser.add_argument("--skip-pinn", action="store_true",
                        help="Skip PINN training (use saved models)")
    parser.add_argument("--separate-plots", action="store_true",
                        help="Also save standalone output/error heatmaps per variable")
    return parser.parse_args()


# --- Train + Evaluate a single ellipse geometry ---
def run_case(cfg: StenosisConfig, a: float, b: float,
             skip_fem: bool, skip_pinn: bool, separate_plots: bool):

    cfg.make_dirs(a, b)
    dirs = cfg.case_dirs(a, b)
    tag  = cfg.case_tag(a, b)
    print(f"\n{'='*60}\nCase: {tag}\n{'='*60}")

    # --- Mesh ---
    msh_file = f"{cfg.meshes_dir}/stenosis_{tag}.msh"
    create_stenosis_mesh(cfg, a, b, msh_file)

    # --- FEM ground truth ---
    fem_file = f"{dirs['fem']}/solution.npz"
    if not skip_fem:
        msh, u_sol, p_sol = solve_stenosis(cfg, msh_file)
        
        # Save on a dense evaluation grid for later comparison
        xs = np.linspace(-cfg.L/2, cfg.L/2, cfg.nx)
        ys = np.linspace(0, cfg.H_max, cfg.ny)
        XX, YY = np.meshgrid(xs, ys)
        flat = np.column_stack([XX.ravel(), YY.ravel()])
        # Mask out points inside the ellipse obstruction
        mask = ellipse_mask(flat[:, 0], flat[:, 1], cfg, a, b)
        query = flat[mask]
        
        fem_vals = fem_predict(u_sol, p_sol, msh, query)    # also holds query pts
        np.savez(fem_file, query=query, vals=fem_vals)
        print(f"FEM solution saved to {fem_file}")
    else:
        print(f"Skipping FEM, loading from {fem_file}")

    # --- PINN ---
    model_prefix = f"{dirs['pinn']}/model"
    if not skip_pinn:
        cfg.clear_pinn(a, b)    # clear old models
        model, loss_history = train_model(cfg, a, b, model_prefix)
        plot_loss_curves(loss_history, dirs['plots'])
    else:
        model = restore_model(cfg, a, b, model_prefix)

    # --- Analysis ---
    fem_file = np.load(fem_file, allow_pickle=True)
    query    = fem_file['query']
    fem_vals = fem_file['vals']

    pinn_vals = pinn_predict(model, query, cfg, a, b)
    errors    = compute_errors(pinn_vals, fem_vals)
    save_errors(errors, dirs['base'], tag)

    plot_domain(cfg, a, b, dirs['plots'])
    plot_output_heatmaps(pinn_vals, fem_vals, cfg, tag, dirs['plots'], a, b, separate_plots)
    plot_error_heatmaps(pinn_vals, fem_vals, cfg, tag, dirs['plots'], a, b, separate_plots)
    print(f"\nAnalysis and Visualization complete.")

    return errors



def main():
    args = parse_args()
    cfg  = StenosisConfig()

    # Override config with CLI args
    if args.re:
        cfg.Re = args.re
    if args.n_adam:
        cfg.n_adam = args.n_adam
    if args.n_lbfgs:
        cfg.n_lbfgs = args.n_lbfgs
    if args.mesh_size:
        cfg.mesh_size = args.mesh_size

    os.makedirs(cfg.meshes_dir, exist_ok=True)
    os.makedirs(cfg.results_dir, exist_ok=True)

    all_errors = {}
    for (a, b) in cfg.cases:
        errors = run_case(cfg, a, b,
                          skip_fem=args.skip_fem,
                          skip_pinn=args.skip_pinn,
                          separate_plots=args.separate_plots)
        all_errors[cfg.case_tag(a, b)] = errors

    # Summary across all cases
    summary_path = os.path.join(cfg.results_dir, "summary.json")
    with open(summary_path, "w") as f:
        json.dump(all_errors, f, indent=2)
    print(f"\nSummary written to {summary_path}")


if __name__ == "__main__":
    main()