# fem.py

"""
2D Parameterized Stenosis
    Ground truth Finite Element Method (FEM) using FEniCS / dolfinx library

Evan Hackstadt
Rugonyi Lab
"""

# Note: bulk of the script generated by Claude Sonnet 4.6


import yaml
import numpy as np

import gmsh
import dolfinx
import ufl
from mpi4py import MPI
import dolfinx.geometry as dgeom
from dolfinx import mesh as dmesh, fem, io
from dolfinx.fem import petsc as fem_petsc
from dolfinx.io import gmsh as gmshio
from basix.ufl import element, mixed_element
from ufl import split, TestFunctions, derivative, dx, grad, div, inner
from petsc4py import PETSc




# ———————————— FEM FUNCTIONS ————————————

# --- Sub-function 1 ---
def build_function_space_and_bcs(msh, facet_tags, cfg):
    # --- Function space ---
    
    # Velocity: vector-valued P2 (quadratic, 2 components)
    P2 = element("Lagrange", msh.topology.cell_name(), 2, shape=(2,))

    # Pressure: scalar P1 (linear)
    P1 = element("Lagrange", msh.topology.cell_name(), 1)

    # Taylor-Hood mixed space
    TH = mixed_element([P2, P1])
    W  = fem.functionspace(msh, TH)

    # Test functions only
    v, q = TestFunctions(W)

    # Current solution (for Newton linearization)
    w  = fem.Function(W)
    u0, p0 = split(w)       # w.split() was causing bugs

    # --- Boundary conditions ---
    # Identify facets by their physical group tag (set in Gmsh)
    inlet_facets   = facet_tags.find(1)
    outlet_facets  = facet_tags.find(2)
    wall_facets    = np.concatenate([
        facet_tags.find(3),  # bottom wall
        facet_tags.find(4),  # top wall
        facet_tags.find(5),  # obstacle
    ])

    # Collapse subspaces into standalone function spaces
    W0, W0_map = W.sub(0).collapse()
    W1, W1_map = W.sub(1).collapse()

    # No-slip on walls
    u_zero = fem.Function(W0)
    u_zero.x.array[:] = 0.0

    # Pass only the collapsed space, not the tuple
    wall_dofs_2d = fem.locate_dofs_topological(
        (W.sub(0), W0),
        msh.topology.dim - 1,
        wall_facets
    )
    # # Row 0 = mixed space DOFs, row 1 = collapsed space DOFs
    # wall_dofs_collapsed = np.array(wall_dofs_2d[1], dtype=np.int32, order='C')

    # bc_walls = fem.dirichletbc(u_zero, wall_dofs_collapsed)
    bc_walls = fem.dirichletbc(u_zero, wall_dofs_2d, W.sub(0))

    '''
    # Inlet pressure
    p_in_func = fem.Function(W1)
    p_in_func.x.array[:] = cfg.P1

    inlet_dofs_collapsed = np.array(
        fem.locate_dofs_topological(
            (W.sub(1), W1), msh.topology.dim - 1, inlet_facets
        )[1], dtype=np.int32, order='C'
    )
    bc_inlet_p = fem.dirichletbc(p_in_func, inlet_dofs_collapsed)

    # Outlet pressure
    p_out_func = fem.Function(W1)
    p_out_func.x.array[:] = cfg.P2

    outlet_dofs_collapsed = np.array(
        fem.locate_dofs_topological(
            (W.sub(1), W1), msh.topology.dim - 1, outlet_facets
        )[1], dtype=np.int32, order='C'
    )
    bc_outlet_p = fem.dirichletbc(p_out_func, outlet_dofs_collapsed)

    bcs = [bc_walls, bc_inlet_p, bc_outlet_p]
    '''
    bcs = [bc_walls]
    
    # Boundary integration measure using your Gmsh facet tags
    ds = ufl.Measure("ds", domain=msh, subdomain_data=facet_tags)
    n = ufl.FacetNormal(msh)
    
    return W, bcs, ds, n


# --- Sub-function 2 ---
def solve_navier_stokes(W, msh, bcs, ds, n, cfg, w_init=None):
    """Solve full N-S using Stokes solution as initial condition."""
    
    w = fem.Function(W)

    if w_init is not None:
        w.x.array[:] = w_init.x.array
        w.x.scatter_forward()

    u0, p0 = split(w)
    v, q   = TestFunctions(W)
        
    # Iteratively solve from easy low Re --> high Re
    # E.g., stepping from Re=10 (near-Stokes) to Re=1000 (target) in 10 steps
    re_steps = np.logspace(np.log10(10.0), np.log10(cfg.Re), num=10)
    
    # Initialize with the lowest Reynolds number in your sequence
    nu = fem.Constant(msh, PETSc.ScalarType(1.0 / re_steps[0]))

    F = (
        inner(grad(u0) * u0, v) * dx
        + nu * inner(grad(u0), grad(v)) * dx
        - p0 * div(v) * dx
        + q  * div(u0) * dx
    )
    J = derivative(F, w)
    
    # Weak boundary integrals for pressure 
    # (Sign convention dictates adding this term for normal inflow/outflow)
    F += cfg.P1 * ufl.inner(n, v) * ds(1) + cfg.P2 * ufl.inner(n, v) * ds(2)

    problem = fem_petsc.NonlinearProblem(F, w, bcs=bcs, J=J,
                               petsc_options_prefix="ns_")

    snes_prefix = problem.solver.getOptionsPrefix()
    PETSc.Options()[f"{snes_prefix}snes_monitor"]          = None
    PETSc.Options()[f"{snes_prefix}snes_converged_reason"] = None
    PETSc.Options()[f"{snes_prefix}snes_max_it"]           = 50
    PETSc.Options()[f"{snes_prefix}snes_rtol"]             = 1e-8
    PETSc.Options()[f"{snes_prefix}snes_atol"]             = 1e-10
    PETSc.Options()[f"{snes_prefix}snes_linesearch_type"]  = "bt"
    PETSc.Options()[f"{snes_prefix}ksp_type"]              = "preonly"
    PETSc.Options()[f"{snes_prefix}pc_type"]               = "lu"
    PETSc.Options()[f"{snes_prefix}pc_factor_mat_solver_type"] = "mumps"
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_24"]    = 1
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_25"]    = 0
    problem.solver.setFromOptions()

    # Solve nonlinear problem
    for current_re in re_steps:
        # Update the kinematic viscosity dynamically
        nu.value = 1.0 / current_re
        
        PETSc.Sys.Print(f"Solving N-S for Re = {current_re:.1f}")
        
        # Solve the non-linear problem
        # w.x.petsc_vec contains the previous solution (or w_stokes initially)
        problem.solver.solve(None, w.x.petsc_vec)
        
        # Scatter forward to update parallel ghost values
        w.x.scatter_forward()
        
        converged = problem.solver.getConvergedReason() > 0
        if not converged:
            PETSc.Sys.Print(f"Solver diverged at Re = {current_re}. Halting.")
            break

    # Query solver for status and iterations
    converged = problem.solver.getConvergedReason() > 0
    try:
        n_iters = problem.solver.getIterationNumber()
    except Exception:
        n_iters = getattr(problem.solver, 'its', None)

    print(f"N-S converged: {converged} in {n_iters} iterations")
    return w


# --- FEM Solver ---
def solve_stenosis(cfg, msh_file):
    msh, cell_t, facet_tags, edge_t, vtx_t, phys_g = gmshio.read_from_msh(
        msh_file, MPI.COMM_WORLD, gdim=2
    )
    msh.topology.create_connectivity(msh.topology.dim - 1, msh.topology.dim)

    W, bcs, ds, n = build_function_space_and_bcs(msh, facet_tags, cfg)

    # Two-stage solve: Stokes → N-S
    # w_stokes = solve_stokes(W, msh, bcs, cfg) 
    w_ns     = solve_navier_stokes(W, msh, bcs, ds, n, cfg)
    
    u_sol, p_sol = w_ns.split()
    return msh, u_sol, p_sol


# --- Get FEM Outputs (Ground Truth) ---
def fem_predict(u_sol, p_sol, msh, query: np.ndarray):
    """
    Evaluate FEM solution at arbitrary (x, y) coordinates.

    query: np.ndarray of (x,y) coordinates with shape (N, 2)
    Returns: ndarray of shape (N, 5) with columns = [x, y, u_pred, v_pred, p_pred]
    """
    query_f32 = query.astype(np.float32)
    
    # FEniCS requires 3D points even for 2D problems
    pts_3d = np.hstack([query_f32, np.zeros((len(query), 1))])

    bb_tree = dgeom.bb_tree(msh, msh.topology.dim)
    cells   = []
    points_on_proc = []

    # Find which cell each query point lives in
    cell_candidates = dgeom.compute_collisions_points(bb_tree, pts_3d)
    colliding_cells = dgeom.compute_colliding_cells(msh, cell_candidates, pts_3d)

    for i, pt in enumerate(pts_3d):
        if len(colliding_cells.links(i)) > 0:
            points_on_proc.append(pt)
            cells.append(colliding_cells.links(i)[0])
        else:   # not in a cell ==> outside boundary, predict 0
            points_on_proc.append(np.zeros_like(pt))
            cells.append(0)
 
    points_on_proc = np.array(points_on_proc)

    u_vals = u_sol.eval(points_on_proc, cells)[:, 0:1]  # shape (N, 1)
    v_vals = u_sol.eval(points_on_proc, cells)[:, 1:2]  # shape (N, 1)
    p_vals = p_sol.eval(points_on_proc, cells)  # shape (N, 1)

    return np.concatenate([query_f32, u_vals, v_vals, p_vals], axis=1)
    
    
    
    
'''
# --- OLD SINGLE FUNCTION FEM SOLVER ---
def solve_stenosis(cfg, msh_file):
    """
    Solve steady incompressible Navier-Stokes on the stenotic channel mesh.
    Returns: (mesh, u_solution, p_solution)
    """
    # --- Load mesh ---
    msh, cell_t, facet_tags, edge_t, vtx_t, phys_g = gmshio.read_from_msh(
        msh_file, MPI.COMM_WORLD, gdim=2
    )

    # --- Function space ---
    
    # Velocity: vector-valued P2 (quadratic, 2 components)
    P2 = element("Lagrange", msh.topology.cell_name(), 2, shape=(2,))

    # Pressure: scalar P1 (linear)
    P1 = element("Lagrange", msh.topology.cell_name(), 1)

    # Taylor-Hood mixed space
    TH = mixed_element([P2, P1])
    W  = fem.functionspace(msh, TH)

    # Test functions only
    v, q = TestFunctions(W)

    # Current solution (for Newton linearization)
    w  = fem.Function(W)
    u0, p0 = split(w)       # w.split() was causing bugs

    # --- Boundary conditions ---
    # Identify facets by their physical group tag (set in Gmsh)
    inlet_facets   = facet_tags.find(1)
    outlet_facets  = facet_tags.find(2)
    wall_facets    = np.concatenate([
        facet_tags.find(3),  # bottom wall
        facet_tags.find(4),  # top wall
        facet_tags.find(5),  # obstacle
    ])

    # Collapse subspaces into standalone function spaces
    W0, W0_map = W.sub(0).collapse()
    W1, W1_map = W.sub(1).collapse()

    # No-slip on walls
    u_zero = fem.Function(W0)
    u_zero.x.array[:] = 0.0

    # Pass only the collapsed space, not the tuple
    wall_dofs_2d = fem.locate_dofs_topological(
        (W.sub(0), W0),
        msh.topology.dim - 1,
        wall_facets
    )
    # Row 0 = mixed space DOFs, row 1 = collapsed space DOFs
    wall_dofs_collapsed = np.array(wall_dofs_2d[1], dtype=np.int32, order='C')

    bc_walls = fem.dirichletbc(u_zero, wall_dofs_collapsed)

    # Inlet pressure
    p_in_func = fem.Function(W1)
    p_in_func.x.array[:] = cfg.P1

    inlet_dofs_collapsed = np.array(
        fem.locate_dofs_topological(
            (W.sub(1), W1), msh.topology.dim - 1, inlet_facets
        )[1], dtype=np.int32, order='C'
    )
    bc_inlet_p = fem.dirichletbc(p_in_func, inlet_dofs_collapsed)

    # Outlet pressure
    p_out_func = fem.Function(W1)
    p_out_func.x.array[:] = cfg.P2

    outlet_dofs_collapsed = np.array(
        fem.locate_dofs_topological(
            (W.sub(1), W1), msh.topology.dim - 1, outlet_facets
        )[1], dtype=np.int32, order='C'
    )
    bc_outlet_p = fem.dirichletbc(p_out_func, outlet_dofs_collapsed)

    bcs = [bc_walls, bc_inlet_p, bc_outlet_p]

    
    """Solve Stokes to get initial condition for N-S Newton iteration."""
    w_stokes = fem.Function(W)
    u0, p0   = split(w_stokes)
    v, q     = TestFunctions(W)

    nu = 1.0 / cfg.Re

    F_stokes = (
          nu * inner(grad(u0), grad(v)) * dx
        - p0 * div(v) * dx
        + q  * div(u0) * dx
    )
    J_stokes = derivative(F_stokes, w_stokes)

    problem = fem_petsc.NonlinearProblem(F_stokes, w_stokes, bcs=bcs, J=J_stokes,
                               petsc_options_prefix="stokes_")

    snes_prefix = problem.solver.getOptionsPrefix()
    PETSc.Options()[f"{snes_prefix}ksp_type"]  = "preonly"
    PETSc.Options()[f"{snes_prefix}pc_type"]   = "lu"
    PETSc.Options()[f"{snes_prefix}pc_factor_mat_solver_type"] = "mumps"
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_24"] = 1
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_25"] = 0
    problem.solver.setFromOptions()

    problem.solver.solve(None, w_stokes.x.petsc_vec)
    w_stokes.x.scatter_forward()

    converged = problem.solver.getConvergedReason() > 0
    print(f"Stokes converged: {converged}")
    
    
    
    # DEBUGGING
    # Assemble just the residual at w=0 and inspect it
    F_form = form(F_stokes)
    b = assemble_vector(F_form)
    print(f"Before lifting - norm: {b.norm():.3e}")
    print(f"Before lifting - max:  {np.abs(b.getArray()).max():.3e}")

    apply_lifting(b, [form(J_stokes)], bcs=[bcs])
    b.ghostUpdate(addv=PETSc.InsertMode.ADD, mode=PETSc.ScatterMode.REVERSE)
    print(f"After lifting  - norm: {b.norm():.3e}")
    print(f"After lifting  - max:  {np.abs(b.getArray()).max():.3e}")

    set_bc(b, bcs)
    print(f"After set_bc   - norm: {b.norm():.3e}")
    print(f"After set_bc   - max:  {np.abs(b.getArray()).max():.3e}")

    # Check each BC's DOFs and values
    print(f"\np_in  value: {p_in_func.x.array.max():.3e}")
    print(f"p_out value: {p_out_func.x.array.max():.3e}")
    print(f"u_zero max:  {u_zero.x.array.max():.3e}")

    # Check DOF arrays for out-of-range indices
    print(f"\nMatrix size:        {33576}")
    print(f"inlet_dofs  max:    {inlet_dofs_collapsed.max() if len(inlet_dofs_collapsed) else 'empty'}")
    print(f"outlet_dofs max:    {outlet_dofs_collapsed.max() if len(outlet_dofs_collapsed) else 'empty'}")
    print(f"wall_dofs   max:    {wall_dofs_collapsed.max() if len(wall_dofs_collapsed) else 'empty'}")
    
    W0, W0_map = W.sub(0).collapse()
    W1, W1_map = W.sub(1).collapse()

    print(f"Velocity space size:  {W0.dofmap.index_map.size_global * W0.dofmap.index_map_bs}")
    print(f"Pressure space size:  {W1.dofmap.index_map.size_global}")
    print(f"Mixed space size:     {W.dofmap.index_map.size_global * W.dofmap.index_map_bs}")

    print(f"\ninlet_dofs  range: [{inlet_dofs_collapsed.min()}, {inlet_dofs_collapsed.max()}]")
    print(f"outlet_dofs range: [{outlet_dofs_collapsed.min()}, {outlet_dofs_collapsed.max()}]")
    print(f"wall_dofs   range: [{wall_dofs_collapsed.min()}, {wall_dofs_collapsed.max()}]")
    
    
    
    """Solve full N-S using Stokes solution as initial condition."""
    w_init = w_stokes
    w      = fem.Function(W)

    # Warm-start from Stokes solution
    if w_init is not None:
        w.x.array[:] = w_init.x.array
        w.x.scatter_forward()

    u0, p0 = split(w)
    v, q   = TestFunctions(W)

    nu = 1.0 / cfg.Re

    F = (
          inner(grad(u0) * u0, v) * dx
        + nu * inner(grad(u0), grad(v)) * dx
        - p0 * div(v) * dx
        + q  * div(u0) * dx
    )
    J = derivative(F, w)

    problem = fem_petsc.NonlinearProblem(F, w, bcs=bcs, J=J,
                               petsc_options_prefix="ns_")

    snes_prefix = problem.solver.getOptionsPrefix()
    PETSc.Options()[f"{snes_prefix}snes_monitor"]          = None
    PETSc.Options()[f"{snes_prefix}snes_converged_reason"] = None
    PETSc.Options()[f"{snes_prefix}snes_max_it"]           = 50
    PETSc.Options()[f"{snes_prefix}snes_rtol"]             = 1e-8
    PETSc.Options()[f"{snes_prefix}snes_atol"]             = 1e-10
    PETSc.Options()[f"{snes_prefix}snes_linesearch_type"]  = "bt"
    PETSc.Options()[f"{snes_prefix}ksp_type"]              = "preonly"
    PETSc.Options()[f"{snes_prefix}pc_type"]               = "lu"
    PETSc.Options()[f"{snes_prefix}pc_factor_mat_solver_type"] = "mumps"
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_24"]    = 1
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_25"]    = 0
    problem.solver.setFromOptions()

    problem.solver.solve(None, w.x.petsc_vec)
    w.x.scatter_forward()

    converged = problem.solver.getConvergedReason() > 0
    n_iters   = problem.solver.getIterationNumber()
    print(f"N-S converged: {converged} in {n_iters} iterations")

    assert converged, "Navier-Stokes solver did not converge"
    

    # --- Weak form (Newton linearization of steady N-S) ---
    # Kinematic viscosity
    nu = 1.0 / cfg.Re

    # Residual F — linear in (v, q), nonlinear in (u0, p0)
    # No TrialFunctions anywhere here
    F = (
        inner(grad(u0) * u0, v) * dx        # convective term (linearized)
        + nu * inner(grad(u0), grad(v)) * dx    # viscous term
        - p0 * div(v) * dx                  # pressure-velocity coupling
        + q * div(u0) * dx                  # continuity
    )

    # Jacobian: derivative of F with respect to w (auto-computed)
    J = derivative(F, w)
    

    # --- Nonlinear solver ---
    problem = fem_petsc.NonlinearProblem(F, w,
                                         petsc_options_prefix="stenosis_",
                                         bcs=bcs, J=J)
    
    # Discover prefixes dynamically rather than assuming
    snes_prefix     = problem.solver.getOptionsPrefix()
    jacobian_prefix = problem.A.getOptionsPrefix()
    
    # Configure the Newton solver via discovered prefix
    PETSc.Options()[f"{snes_prefix}snes_type"]     = "newtonls"
    PETSc.Options()[f"{snes_prefix}snes_rtol"]     = 1e-8
    PETSc.Options()[f"{snes_prefix}snes_atol"]     = 1e-10
    PETSc.Options()[f"{snes_prefix}snes_max_it"]   = 50
    PETSc.Options()[f"{snes_prefix}snes_linesearch_type"] = "bt"  # backtracking
    
    # Direct solver for the linear subproblem — most robust for this system size
    PETSc.Options()[f"{snes_prefix}ksp_type"]    = "preonly"
    PETSc.Options()[f"{snes_prefix}pc_type"]     = "lu"
    
    # MUMPS options for saddle-point stability
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_24"] = 1     # detect null pivots
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_25"] = 0     # don't try to fix them
    
    # Monitoring
    PETSc.Options()[f"{snes_prefix}snes_monitor"] = None
    PETSc.Options()[f"{snes_prefix}snes_converged_reason"] = None
    PETSc.Options()[f"{snes_prefix}ksp_monitor"] = None
    PETSc.Options()[f"{snes_prefix}ksp_converged_reason"] = None
    
    problem.solver.setFromOptions()
    
    # DEBUGGING
    # Assemble residual at zero initial condition and check norm
    F_form = form(F)
    b_vec  = assemble_vector(F_form)
    b_vec.ghostUpdate(addv=PETSc.InsertMode.ADD,
                    mode=PETSc.ScatterMode.REVERSE)
    print(f"Initial residual norm: {b_vec.norm()}")
    print(f"Residual size: {b_vec.getSize()}")
    
    # Wire up the DM to the solution vector directly
    problem.solver.setSolution(w.x.petsc_vec)
    
    # Solve
    # pass None as the initial guess arg since solution vector is already set
    problem.solver.solve(None, w.x.petsc_vec)
    w.x.scatter_forward()
    
    assert problem.solver.getConvergedReason() > 0
    
    # Return
    converged = problem.solver.is_converged
    n_iters = problem.solver.its
    print(f"Newton converged: {converged} in {n_iters} iterations")

    u_sol, p_sol = w.split()
    return msh, u_sol, p_sol
'''