# fem.py

"""
2D Parameterized Stenosis
    Ground truth Finite Element Method (FEM) using FEniCS / dolfinx library

Evan Hackstadt
Rugonyi Lab
"""

# Note: bulk of the script generated by Claude Sonnet 4.6


import yaml
import numpy as np

import gmsh
import dolfinx
import ufl
from mpi4py import MPI
import dolfinx.geometry as dgeom
from dolfinx import mesh as dmesh, fem, io
from dolfinx.fem import petsc as fem_petsc
from dolfinx.io import gmsh as gmshio
from basix.ufl import element, mixed_element
from ufl import split, TestFunctions, derivative, dx, grad, div, inner
from petsc4py import PETSc

from pinn import inlet_u, set_global_constants


# ———————————— FEM FUNCTIONS ————————————

# --- Sub-function 1 ---
def build_function_space_and_bcs(msh, facet_tags, cfg):
    # inlet_u() needs global H_MAX on the call stack; use dummy a and b
    set_global_constants(cfg, 0.0, 0.0)
    
    # --- Function space ---
    
    # Velocity: vector-valued P2 (quadratic, 2 components)
    P2 = element("Lagrange", msh.topology.cell_name(), 2, shape=(2,))

    # Pressure: scalar P1 (linear)
    P1 = element("Lagrange", msh.topology.cell_name(), 1)

    # Taylor-Hood mixed space
    TH = mixed_element([P2, P1])
    W  = fem.functionspace(msh, TH)

    # Test functions only
    v, q = TestFunctions(W)

    # Current solution (for Newton linearization)
    w  = fem.Function(W)
    u0, p0 = split(w)       # w.split() was causing bugs

    # --- Boundary conditions ---
    # Identify facets by their physical group tag (set in Gmsh)
    inlet_facets   = facet_tags.find(1)
    outlet_facets  = facet_tags.find(2)
    wall_facets    = np.concatenate([
        facet_tags.find(3),  # bottom wall
        facet_tags.find(4),  # top wall
        facet_tags.find(5),  # obstacle
    ])

    # Collapse subspaces into standalone function spaces
    W0, W0_map = W.sub(0).collapse()
    W1, W1_map = W.sub(1).collapse()

    # No-slip on walls
    u_zero = fem.Function(W0)
    u_zero.x.array[:] = 0.0

    # Pass only the collapsed space, not the tuple
    wall_dofs_2d = fem.locate_dofs_topological(
        (W.sub(0), W0),
        msh.topology.dim - 1,
        wall_facets
    )
    bc_walls = fem.dirichletbc(u_zero, wall_dofs_2d, W.sub(0))

    # Inlet velocity profile (parabolic Poiseuille)
    u_in = fem.Function(W0)

    def inlet_profile(x):
        pts = np.asarray(x).T
        profile = inlet_u(pts).reshape(-1)
        return np.vstack((profile, np.zeros_like(profile)))

    u_in.interpolate(inlet_profile)

    inlet_dofs_2d = fem.locate_dofs_topological(
        (W.sub(0), W0),
        msh.topology.dim - 1,
        inlet_facets
    )
    bc_inlet = fem.dirichletbc(u_in, inlet_dofs_2d, W.sub(0))
    
    bcs = [bc_walls, bc_inlet]
    
    # Boundary integration measure using your Gmsh facet tags
    ds = ufl.Measure("ds", domain=msh, subdomain_data=facet_tags)
    n = ufl.FacetNormal(msh)
    
    return W, bcs, ds, n


# --- Sub-function 2 ---
def solve_navier_stokes(W, msh, bcs, ds, n, cfg, w_init=None):
    """Solve full N-S using Stokes solution as initial condition."""
    
    w = fem.Function(W)

    if w_init is not None:
        w.x.array[:] = w_init.x.array
        w.x.scatter_forward()

    u0, p0 = split(w)
    v, q   = TestFunctions(W)
        
    # Iteratively solve from easy low Re --> high Re
    # E.g., stepping from Re=10 (near-Stokes) to Re=1000 (target) in 10 steps
    re_steps = np.logspace(np.log10(10.0), np.log10(cfg.Re), num=10)
    
    # Initialize with the lowest Reynolds number in your sequence
    nu = fem.Constant(msh, PETSc.ScalarType(1.0 / re_steps[0]))

    F = (
        inner(grad(u0) * u0, v) * dx
        + nu * inner(grad(u0), grad(v)) * dx
        - p0 * div(v) * dx
        + q  * div(u0) * dx
    )
    J = derivative(F, w)
    
    # Weak boundary integral for outlet pressure
    # (Sign convention dictates adding this term for normal outflow)
    F += cfg.P_out * ufl.inner(n, v) * ds(2)

    problem = fem_petsc.NonlinearProblem(F, w, bcs=bcs, J=J,
                               petsc_options_prefix="ns_")

    snes_prefix = problem.solver.getOptionsPrefix()
    PETSc.Options()[f"{snes_prefix}snes_monitor"]          = None
    PETSc.Options()[f"{snes_prefix}snes_converged_reason"] = None
    PETSc.Options()[f"{snes_prefix}snes_max_it"]           = 50
    PETSc.Options()[f"{snes_prefix}snes_rtol"]             = 1e-8
    PETSc.Options()[f"{snes_prefix}snes_atol"]             = 1e-10
    PETSc.Options()[f"{snes_prefix}snes_linesearch_type"]  = "bt"
    PETSc.Options()[f"{snes_prefix}ksp_type"]              = "preonly"
    PETSc.Options()[f"{snes_prefix}pc_type"]               = "lu"
    PETSc.Options()[f"{snes_prefix}pc_factor_mat_solver_type"] = "mumps"
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_24"]    = 1
    PETSc.Options()[f"{snes_prefix}mat_mumps_icntl_25"]    = 0
    problem.solver.setFromOptions()

    # Solve nonlinear problem
    for current_re in re_steps:
        # Update the kinematic viscosity dynamically
        nu.value = 1.0 / current_re
        
        PETSc.Sys.Print(f"Solving N-S for Re = {current_re:.1f}")
        
        # Solve the non-linear problem
        # w.x.petsc_vec contains the previous solution (or w_stokes initially)
        problem.solver.solve(None, w.x.petsc_vec)
        
        # Scatter forward to update parallel ghost values
        w.x.scatter_forward()
        
        converged = problem.solver.getConvergedReason() > 0
        if not converged:
            PETSc.Sys.Print(f"Solver diverged at Re = {current_re}. Halting.")
            break

    # Query solver for status and iterations
    converged = problem.solver.getConvergedReason() > 0
    try:
        n_iters = problem.solver.getIterationNumber()
    except Exception:
        n_iters = getattr(problem.solver, 'its', None)

    print(f"N-S converged: {converged} in {n_iters} iterations")
    return w


# --- FEM Solver ---
def solve_stenosis(cfg, msh_file):
    msh, cell_t, facet_tags, edge_t, vtx_t, phys_g = gmshio.read_from_msh(
        msh_file, MPI.COMM_WORLD, gdim=2
    )
    msh.topology.create_connectivity(msh.topology.dim - 1, msh.topology.dim)

    W, bcs, ds, n = build_function_space_and_bcs(msh, facet_tags, cfg)

    # Solve
    w = solve_navier_stokes(W, msh, bcs, ds, n, cfg)
    
    u_sol, p_sol = w.split()
    return msh, u_sol, p_sol


# --- Get FEM Outputs (Ground Truth) ---
def fem_predict(u_sol, p_sol, msh, query: np.ndarray):
    """
    Evaluate FEM solution at arbitrary (x, y) coordinates.

    query: np.ndarray of (x,y) coordinates with shape (N, 2)
    Returns: ndarray of shape (N, 5) with columns = [x, y, u_pred, v_pred, p_pred]
    """
    query_f32 = query.astype(np.float32)
    
    # FEniCS requires 3D points even for 2D problems
    pts_3d = np.hstack([query_f32, np.zeros((len(query), 1))])

    bb_tree = dgeom.bb_tree(msh, msh.topology.dim)
    cells   = []
    points_on_proc = []

    # Find which cell each query point lives in
    cell_candidates = dgeom.compute_collisions_points(bb_tree, pts_3d)
    colliding_cells = dgeom.compute_colliding_cells(msh, cell_candidates, pts_3d)

    for i, pt in enumerate(pts_3d):
        if len(colliding_cells.links(i)) > 0:
            points_on_proc.append(pt)
            cells.append(colliding_cells.links(i)[0])
        else:   # not in a cell ==> outside boundary, predict 0
            raise ValueError("Query point outside of boundary")
 
    points_on_proc = np.array(points_on_proc)

    u_vals = u_sol.eval(points_on_proc, cells)[:, 0:1]  # shape (N, 1)
    v_vals = u_sol.eval(points_on_proc, cells)[:, 1:2]  # shape (N, 1)
    p_vals = p_sol.eval(points_on_proc, cells)  # shape (N, 1)

    return np.concatenate([query_f32, u_vals, v_vals, p_vals], axis=1)
