# main.py

"""
2D Parameterized Stenosis
    Main script and CLI entry point; calls other scripts
Evan Hackstadt
Rugonyi Lab
"""

# Note: bulk of the script generated by Claude Sonnet 4.6
# Note: script currently cannot train over multiple geometries; 
#       rather it can just run multiple independently


import json
import argparse
from pathlib import Path

import numpy as np
import torch
import deepxde as dde

from config import StenosisConfig
from geometry import create_stenosis_mesh, ellipse_bottom, ellipse_mask
from fem import solve_stenosis, fem_predict
from pinn import build_labeled_sequence, train_model, restore_model, pinn_predict
from analysis import (compute_errors, save_errors,
                      plot_loss_curves, plot_domain,
                      plot_output_heatmaps, plot_error_heatmaps,
                      plot_error_comparison, plot_error_comparison_2d)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--re",        type=float, help="Reynolds number")
    parser.add_argument("--n-adam",    type=int,   help="Adam iterations")
    parser.add_argument("--n-lbfgs",   type=int,   help="L-BFGS iterations")
    parser.add_argument("--mesh-size", type=float, help="FEM mesh element size")
    parser.add_argument("--skip-mesh",  action="store_true",
                        help="Skip mesh generation (use cached file)")
    parser.add_argument("--skip-fem",  action="store_true",
                        help="Skip FEM solve (use cached results)")
    parser.add_argument("--skip-pinn", action="store_true",
                        help="Skip PINN training (use saved models)")
    parser.add_argument("--skip-complete", action="store_true",
                        help="Skip cases that appear complete based on existing outputs")
    parser.add_argument("--separate-plots", action="store_true",
                        help="Also save standalone output/error heatmaps per variable")
    parser.add_argument("--fem-only", action="store_true",
                        help="Run only the FEM simulations, skipping PINN and analysis/visualization completely.")
    return parser.parse_args()


def case_complete(cfg: StenosisConfig, a: float, b: float, n_labeled: int):
    dirs = cfg.case_dirs(a, b, n_labeled)
    error_path = dirs['base'] / "errors.json"
    plot_dir = dirs['plots']

    if error_path.is_file():
        return True
    if plot_dir.is_dir():
        for fname in plot_dir.iterdir():
            if fname.is_file():
                return True
    return False


def load_case_errors(cfg: StenosisConfig, a: float, b: float, n_labeled: int):
    error_path = cfg.case_dirs(a, b, n_labeled)['base'] / "errors.json"
    if error_path.is_file():
        with error_path.open("r", encoding="utf-8") as f:
            return json.load(f)
    return {
        "status": "skipped",
        "message": "Skipped because existing outputs were detected, but errors.json was not present."
    }


# --- Train + Evaluate a single ellipse geometry ---
def run_case(cfg: StenosisConfig, a: float, b: float, n_labeled: int,
             all_labeled_pts: np.ndarray, fem_data: np.ndarray,
             skip_pinn: bool, separate_plots: bool):

    dirs = cfg.case_dirs(a, b, n_labeled)
    tag  = cfg.case_tag(a, b, n_labeled)
    print(f"\n{'='*50}\nCase: {tag}\n{'='*50}")

    # --- PINN ---
    model_prefix = dirs['pinn'] / "model"
    labeled_pts = all_labeled_pts[:n_labeled] if n_labeled > 0 else None
    
    if not skip_pinn:
        cfg.clear_dir(dirs['pinn'])     # clear old models
        model = train_model(labeled_pts, cfg, a, b, n_labeled, model_prefix)
    else:
        model = restore_model(labeled_pts, cfg, a, b, n_labeled, model_prefix)

    # --- Analysis ---    
    loss_data   = np.loadtxt(dirs['pinn'] / "loss.dat",
                             delimiter=" ", comments="#")
    plot_loss_curves(loss_data, dirs['plots'])
    plot_domain(cfg, a, b, dirs['plots'], labeled_pts)
    
    # get model outputs
    query = fem_data[:, 0:2]
    pinn_data = pinn_predict(model, query)
    
    errors    = compute_errors(pinn_data, fem_data)
    save_errors(errors, dirs['base'], a, b, n_labeled)
    plot_output_heatmaps(pinn_data, fem_data, cfg, tag, dirs['plots'], a, b, separate_plots)
    plot_error_heatmaps(pinn_data, fem_data, cfg, tag, dirs['plots'], a, b, separate_plots)
    
    print(f"\nAnalysis and Visualization complete.")

    return errors


def run_geometry(cfg: StenosisConfig, a: float, b: float,
                 skip_mesh: bool, skip_fem: bool, fem_only: bool):
    
    cfg.make_dirs(a, b)
    dirs = cfg.geo_dirs(a, b)
    tag = cfg.geo_tag(a, b)
    
    # --- Mesh ---
    msh_file = cfg.meshes_dir / f"stenosis_{tag}.msh"
    if not skip_mesh:
        create_stenosis_mesh(cfg, a, b, msh_file)
    else:
        print(f"Skipping mesh, loading from {msh_file}")

    # --- FEM ground truth ---
    fem_file = dirs['fem'] / "solution.npz"
    
    if not skip_fem:    
        msh, u_sol, p_sol = solve_stenosis(cfg, msh_file)
        
        # Save on a dense evaluation grid for later comparison
        xs = np.linspace(-cfg.L/2, cfg.L/2, cfg.nx)
        ys = np.linspace(0, cfg.H_max, cfg.ny)
        XX, YY = np.meshgrid(xs, ys)
        flat = np.column_stack([XX.ravel(), YY.ravel()])
        
        # Mask out points inside the ellipse obstruction
        mask = ellipse_mask(flat[:, 0], flat[:, 1], cfg, a, b)
        query = flat[mask]
        
        # Get FEM vals for the uniform query
        fem_data = fem_predict(u_sol, p_sol, msh, query, cfg)    # fem_data also holds query pts
        np.savez(fem_file, data=fem_data)
        print(f"FEM solution saved to {fem_file}")
        
    else:
        print(f"Skipping FEM, loading from {fem_file}")

    # Reload the ground truth
    fem_file = np.load(fem_file, allow_pickle=True)
    fem_data = fem_file['data']
    query    = fem_data[:, 0:2]
    
    # Sample labeled points first (to enable nested subsampling)
    n_max = max(cfg.n_labeled)
    labeled_points = build_labeled_sequence(fem_data, n_max, cfg, uniform_frac=0.3)
    savepath = dirs["fem"] / f"labeled_points_nmax_{n_max}.csv"
    np.savetxt(savepath, labeled_points, delimiter=",")
    
    return fem_data, labeled_points


def main():
    args = parse_args()
    cfg  = StenosisConfig()

    # Override config with CLI args
    if args.re:
        cfg.Re = args.re
    if args.n_adam:
        cfg.n_adam = args.n_adam
    if args.n_lbfgs:
        cfg.n_lbfgs = args.n_lbfgs
    if args.mesh_size:
        cfg.mesh_size = args.mesh_size

    cfg.meshes_dir.mkdir(parents=True, exist_ok=True)
    cfg.results_dir.mkdir(parents=True, exist_ok=True)

    print(f"Execution Plan: all combinations of\nn={cfg.n_labeled}\n(a,b)={cfg.geometries}")
    
    all_errors = {}
    run_i = 1
    for (a, b) in cfg.geometries:
        
        fem_data, all_labeled_pts = run_geometry(cfg, a, b,
                                                 skip_mesh=args.skip_mesh,
                                                 skip_fem=args.skip_fem,
                                                 fem_only=args.fem_only)
        
        for n in cfg.n_labeled:
            
            cfg.make_dirs(a, b, n)
            
            if args.fem_only:
                print(f"Skipping PINN and analysis...")
                continue
            elif args.skip_complete and case_complete(cfg, a, b, n):
                print(f"Skipping complete case: {cfg.case_tag(a, b, n)}")
                errors = load_case_errors(cfg, a, b, n)
            else:
                errors = run_case(cfg, a, b, n, 
                                  all_labeled_pts, fem_data,
                                  skip_pinn=args.skip_pinn,
                                  separate_plots=args.separate_plots)
            
            all_errors[f"run{run_i}"] = errors
            all_errors[f"run{run_i}"]["parameters"] = {"a": a, "b": b, "n": n}
            run_i += 1

            config_dict = cfg.config_as_dict(a,b,n)
            config_path = cfg.case_dirs(a,b,n)["base"] / "config_log.json"
            with config_path.open("w", encoding="utf-8") as f:
                json.dump(config_dict, f, indent=2)
                

    if not args.fem_only:
        
        # Summary across all cases
        cfg.summary_dir.mkdir(parents=True, exist_ok=True)
        summary_path = cfg.summary_dir / "summary.json"
        with summary_path.open("w") as f:
            json.dump(all_errors, f, indent=2)
        print(f"\nSummary written to {summary_path}")
        
        # Global analysis
        compare_dir = cfg.summary_dir / "summary_plots"
        
        plot_error_comparison(summary_path, compare_dir, "n", fixed_ab=None)    # average across (a,b)
        plot_error_comparison(summary_path, compare_dir, "ab", fixed_n=None)    # average across n
        plot_error_comparison_2d(summary_path, compare_dir, "n", "ab")
        
        print(f"\nGlobal visualization complete, saved to {cfg.summary_dir / "summary_plots"}")


if __name__ == "__main__":
    main()